resolving #158
EddieHubCommunity/EddieHubCommunity.github.io pull request #159
Opened 2021-03-24 17:09 UTC by pvcodes

Hi, I resolved issue #158. @eddiejaoude please give it a green flag.

2021-03-24 17:13 UTC, pvcodes commented
> Hi, I resolved issue #158. @eddiejaoude please give it a green flag.

due to my "format document" of VSCODE, the App.svelte is formatted and that's why this much of insertion and deletion are showing

2021-03-24 17:15 UTC, pvcodes commented
> # Alex Recommends Report
> 
> Alex recommends the following language changes, but Alex is a regular expression based algorithm, so take them with a grain of salt.
> ### sparkles rocket sparkles Nothing to Report sparkles rocket sparkles

Hi, @AllanRegush, this github report bot is soo overwhelming! :smile:

2021-03-30 05:23 UTC, AllanRegush commented
> > # Alex Recommends Report
> > Alex recommends the following language changes, but Alex is a regular expression based algorithm, so take them with a grain of salt.
> > ### sparkles rocket sparkles Nothing to Report sparkles rocket sparkles
> 
> Hi, @AllanRegush, this github report bot is soo overwhelming! smile

Sorry I didn't see this tag. Yeah, there are a lot of messages.

2021-03-30 05:24 UTC, AllanRegush commented
I'll have to pull this down tomorrow and have a look :+1:

2021-04-10 21:57 UTC, eddiejaoude commented
hi @pvcodes , sorry for the slow reply, I am still going through GitHub notifications. Thank you for the changes, someone will take a look soon 👍 

Note, smaller PRs get merged sooner, because they are easier to review. If there are reformatting changes, it is best to do those in a separate PR

2021-04-12 09:56 UTC, schmelto requested changes

2021-04-12 09:56 UTC, schmelto commented on src/App.svelte
> +      alt="" />
```suggestion
      alt="EddieHub Banner" />
```
Maybe add some alternative text here

2021-04-12 10:17 UTC, pvcodes commented on src/App.svelte
> +      alt="" />
Done!

2021-04-16 05:46 UTC, kaiwalyakoparkar requested changes
If you are changing the coding style then please make sure you carry it out in the entire file. :smile: . I would recommend doing this small changes

2021-04-16 05:46 UTC, kaiwalyakoparkar commented on src/App.svelte
>    <h3
You can make this in a line as well

2021-04-16 05:46 UTC, kaiwalyakoparkar commented on src/App.svelte
> +    class="flex flex-col items-center bg-white lg:rounded m-12 py-8 px-4 lg:px-16 lg:max-w-4xl">
Make this in a line as well

2021-04-16 05:46 UTC, kaiwalyakoparkar commented on src/App.svelte
> +    class="flex flex-col items-center bg-white lg:rounded m-12 py-8 px-4 lg:px-16 lg:max-w-4xl">
Can put this in a single line as well

2021-04-16 05:46 UTC, kaiwalyakoparkar commented on src/App.svelte
> +      class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-4">
put this in single line as well

2021-05-06 02:28 UTC, AllanRegush commented
Sorry, I forgot to get back to this PR. Could you make sure the style matches up and only the changes you want to make are in the diff?

2021-05-06 10:39 UTC, pvcodes commented
> Sorry, I forgot to get back to this PR. Could you make sure the style matches up and only the changes you want to make are in the diff?

For sure! the identation messed due to my vscode indenting setting, Sorry for that

2021-05-13 18:51 UTC, eddiejaoude commented
Thank you for the contribution, but I will close this because website moved to low code platform

2021-05-13 18:51 UTC, closed without merging