PR regarding constant IsueTemplates for all repos.
EddieHubCommunity/EddieHubCommunity.github.io pull request #218
Opened 2021-11-26 16:53 UTC by Saurabhpatil-dev

Hello @Panquesito7  @krishguptadev ,

I am creating this PR regarding the issue number #211 .

Please review, and let me know if any changes are required.

2021-11-27 06:38 UTC, krishguptadev approved these changes

2021-11-28 19:11 UTC, Panquesito7 requested changes

2021-11-28 19:11 UTC, Panquesito7 commented on .github/ISSUE_TEMPLATE/bug.yml
>  labels: ["🛠 goal: fix"]
```suggestion
labels: ["bug"]
```

2021-11-28 19:11 UTC, Panquesito7 commented on .github/ISSUE_TEMPLATE/bug.yml
> +      description: A brief description of the question or issue, also include what you tried and what didn't work
```suggestion
      description: A brief description of the question or issue. Also, include what you tried and what didn't work
```

2021-11-28 19:11 UTC, Panquesito7 commented on .github/ISSUE_TEMPLATE/docs.yml
> +labels: ["📄 aspect: text"]
```suggestion
labels: ["documentation"]
```

2021-11-28 19:11 UTC, Panquesito7 commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +labels: ["⭐ goal: addition"]
```suggestion
labels: ["enhancement"]
```

2021-11-29 02:51 UTC, krishguptadev approved these changes

2021-11-29 03:25 UTC, Panquesito7 approved these changes

2022-05-16 20:49 UTC, eddiejaoude approved these changes
Thank you 👍

2022-05-16 20:50 UTC, merged