[FEATURE] Add Links to Partner Icons #310
EddieHubCommunity/EddieHubCommunity.github.io pull request #320
Opened 2023-12-17 10:05 UTC by ninadvyas

`Closes #310 ` Add Links to Partner Icons : #310

## Changes proposed

- Added links to the partner icons

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots of #310 
<img width="1440" alt="Screenshot 2023-12-16 at 3 21 25 PM" src="https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/assets/115214615/0df67b7d-ff1b-4e91-bf4b-900a2c294bc0">

2023-12-28 06:07 UTC, xkrishguptaa commented on src/components/Footer.jsx
> +                      <a href={company.href} target="_blank" title={company.title}>
Please use the nextjs link tag!

2023-12-29 02:49 UTC, ninadvyas commented
@xkrishguptaa I have made changes accordingly as you said.

2023-12-29 11:00 UTC, xkrishguptaa requested changes
Did you import the link tag? Because I do not see it in the imports?

2023-12-29 11:00 UTC, xkrishguptaa commented on src/components/Footer.jsx
> +                      </Link>
```suggestion
                      <Link href={company.href} target="_blank" title={company.title}>
                      	<Image
                        	src={company.logo}
                        	alt={company.name}
                        	unoptimized
                        	width="50"
                      	/>
                      </Link>
```

2023-12-29 15:25 UTC, ninadvyas commented
@xkrishguptaa link tag already there imported at first line of the file. Waiting for the feedback.

2023-12-29 17:30 UTC, xkrishguptaa approved these changes
Ah okay! sorry missed it earlier, thank you for the contribution

2023-12-29 17:31 UTC, merged